name: Publish
on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node.js (npm)
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Get yarn cache
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: yarn install

      - name: Build
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: yarn run build

      - name: Test
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: yarn test

      - name: Report coverage
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: codecov/codecov-action@master
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Bump version
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "smockle/action-version@main"
        env:
          GITHUB_USER_EMAIL: bot@smockle.com
          GITHUB_USER_NAME: smockle-bot
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Publish (npm)
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: "yarn publish --access public --@smockle:registry=https://registry.npmjs.org/"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Setup Node.js (GPR)
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Publish (GPR)
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: "yarn publish --access public --@smockle:registry=https://npm.pkg.github.com/"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
